### ISSUE TITLE
ValueError when run MDANSE-Examples

### ISSUE THREAD

**Issue by WangSimin123456** [ISISNeutronMuon/MDANSE-Examples#8]
Dear all,

I am a new user of MDANSE. When I run this tutorial on Linux, I have the following issue:

Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.11/site-packages/MDANSE/Framework/Jobs/IJob.py", line 387, in run
    self.setup(parameters)
  File "/home/anaconda3/lib/python3.11/site-packages/MDANSE/Framework/Configurable.py", line 170, in setup
    conf.configure(parameters[name])
  File "/home/anaconda3/lib/python3.11/site-packages/MDANSE/Framework/Configurators/OutputTrajectoryConfigurator.py", line 61, in configure
    root, dtype, compression, logs = value
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 4, got 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/structure_analysis/task/tutorial1-phase-transition/mdanse_inputs/script1_conversion.py", line 31, in <module>
    lammps.run(parameters, status=True)
  File "/home/anaconda3/lib/python3.11/site-packages/MDANSE/Framework/Jobs/IJob.py", line 411, in run
    raise JobError(self, tb)
MDANSE.Framework.Jobs.IJob.JobError: Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.11/site-packages/MDANSE/Framework/Jobs/IJob.py", line 387, in run
    self.setup(parameters)
  File "/home/anaconda3/lib/python3.11/site-packages/MDANSE/Framework/Configurable.py", line 170, in setup
    conf.configure(parameters[name])
  File "/home/anaconda3/lib/python3.11/site-packages/MDANSE/Framework/Configurators/OutputTrajectoryConfigurator.py", line 61, in configure
    root, dtype, compression, logs = value
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 4, got 3)

I didn't change any setup in the mdanse_inputs file. And my command was "mdanse --jr script1_conversion.py". Can you tell how to solve these problems? Thanks.

**Comment by WangSimin123456** [comment]
My mdanse version is 2.0.0a2. And I found the mdanse_gui crashed when I clicked the "converters" tab.

**Comment by ChiCheng45** [comment]
Hi, 

script1_conversion.py is run with python. E.g. 

`python script1_conversion.py`.

I'm not able to help you with the mdanse_gui crash without some more details, are there some error messages in the terminal? Does the GUI load at all?

**Comment by ChiCheng45** [comment]
Good to hear the the GUI is working now. It should work with 3.11, it could have something to do with your Python environment and the external libraries that you have installed.

As for the script issue, thanks for spotting that. We made some changes to MDANSE recently which meant that the script only worked for an older version of MDANSE. We will get around to updating them soon.
